# @package _global_
seed: 0
stages:
  - name: train
    overrides:
      - +exp=ppo_roa/train
      - +task/patches=[v1_1,root_global_xyz]
      - total_iters=4000
      - algo.train_every=32
    load_checkpoint_from_previous: false
  - name: adapt
    overrides:
      - +exp=ppo_roa/adapt
      - +task/patches=[v1_1,root_window_xyz]
      - total_iters=1000
      - algo.train_every=16
    load_checkpoint_from_previous: true
  - name: finetune
    overrides:
      - +exp=ppo_roa/finetune
      - +task/patches=[v1_1,root_window_xyz]
      - total_iters=2000
      - algo.train_every=32
    load_checkpoint_from_previous: true
